In [1]:
import numpy as np

In [11]:
arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randn(3, 3)
arr3 = np.random.rand(3, 3)
arr1, arr2, arr3

(array([[8, 4, 8],
        [7, 3, 4],
        [8, 8, 9]]),
 array([[-0.31986508,  0.94427997,  1.11452152],
        [-2.03525462,  2.68225206,  2.27105808],
        [ 1.01602476,  0.36771242,  0.03698789]]),
 array([[0.45681989, 0.55232415, 0.87893965],
        [0.96875259, 0.28927773, 0.9438072 ],
        [0.05432367, 0.27892765, 0.67740517]]))